version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/usr/src/frontend/src
      - ./frontend/public:/usr/src/frontend/public
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: ["npm", "run", "start"]

  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/server
    ports:
      - 8000:8000
    command: ["python", "manage.py", "runserver"]
